
# create a travis env variable to get the first 6 chars of the git commit hash. $TRAVIS_COMMIT has the full hash value.

sudo: required
services:
  - docker
before_script:
  - './bin/test.sh -d'
script:
  - './bin/build.sh -p'
